on:
  push:
    branches:
      - main
      - master

name: build-site

jobs:
  build-site:
    runs-on: ubuntu-22.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        id: install-r

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: Install tidyverse
        run: Rscript -e 'install.packages(c("dplyr", "readr", "ggplot2"))'

      - name: Build website
        run: |
          Rscript -e 'rmarkdown::render_site()'
          touch _site/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
